"""add_avatar_field_to_users

Revision ID: 0e24ef6757e2
Revises: 2d3d9120f611
Create Date: 2025-08-22 14:50:01.688399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e24ef6757e2'
down_revision = '2d3d9120f611'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role_menu', 'auth_mark')
    op.add_column('users', sa.Column('avatar', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar')
    op.add_column('role_menu', sa.Column('auth_mark', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='权限标识，为空表示菜单权限，有值表示具体权限'))
    # ### end Alembic commands ###
