"""add_auth_mark_to_role_menu

Revision ID: 2d3d9120f611
Revises: 87b3f539ff95
Create Date: 2025-08-21 20:37:45.752262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d3d9120f611'
down_revision = '87b3f539ff95'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role_menu', sa.Column('auth_mark', sa.String(length=100), nullable=True, comment='权限标识，为空表示菜单权限，有值表示具体权限'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role_menu', 'auth_mark')
    # ### end Alembic commands ###
