"""Add created_by field to order models

Revision ID: 47e2bd333d83
Revises: 7e4a39d4a71b
Create Date: 2025-09-09 18:52:17.445191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47e2bd333d83'
down_revision = '7e4a39d4a71b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('external_orders', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'external_orders', 'users', ['created_by'], ['id'])
    op.add_column('internal_orders', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'internal_orders', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'internal_orders', type_='foreignkey')
    op.drop_column('internal_orders', 'created_by')
    op.drop_constraint(None, 'external_orders', type_='foreignkey')
    op.drop_column('external_orders', 'created_by')
    # ### end Alembic commands ###
