"""update_user_table_fields

Revision ID: 53997f50e5cf
Revises: change_role_to_roles_array
Create Date: 2025-08-19 17:10:44.280048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53997f50e5cf'
down_revision = 'change_role_to_roles_array'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('create_by', sa.String(), nullable=True))
    op.add_column('users', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('update_by', sa.String(), nullable=True))
    op.add_column('users', sa.Column('update_time', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('status', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('nick_name', sa.String(), nullable=True))
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'nick_name')
    op.drop_column('users', 'status')
    op.drop_column('users', 'update_time')
    op.drop_column('users', 'update_by')
    op.drop_column('users', 'create_time')
    op.drop_column('users', 'create_by')
    # ### end Alembic commands ###
