"""add_system_settings_table

Revision ID: 5dcf4c45a68f
Revises: 03d9b5531d32
Create Date: 2025-09-05 07:56:55.182603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dcf4c45a68f'
down_revision = '03d9b5531d32'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_by', sa.String(), nullable=True),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_by', sa.String(), nullable=True),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('setting_key', sa.String(), nullable=False, comment='配置键'),
    sa.Column('setting_value', sa.Text(), nullable=False, comment='配置值'),
    sa.Column('setting_name', sa.String(), nullable=False, comment='配置名称'),
    sa.Column('setting_desc', sa.String(), nullable=True, comment='配置描述'),
    sa.Column('setting_type', sa.String(), nullable=True, comment='配置类型'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=False)
    op.create_index(op.f('ix_system_settings_setting_key'), 'system_settings', ['setting_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_settings_setting_key'), table_name='system_settings')
    op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
    op.drop_table('system_settings')
    # ### end Alembic commands ###
