"""add_cascade_fields_to_dictionary_enum

Revision ID: 6651bd40ebda
Revises: c293cfa96ab9
Create Date: 2025-09-07 17:20:52.257097

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6651bd40ebda'
down_revision = 'c293cfa96ab9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dic_enums', sa.Column('parent_id', sa.Integer(), nullable=True, comment='父级枚举ID'))
    op.add_column('dic_enums', sa.Column('level', sa.Integer(), nullable=True, comment='层级'))
    op.add_column('dic_enums', sa.Column('path', sa.String(), nullable=True, comment='路径'))
    op.create_foreign_key(None, 'dic_enums', 'dic_enums', ['parent_id'], ['id'])
    op.alter_column('menus', 'is_link',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_comment='是否外链',
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('menus', 'is_link',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_comment='是否外链',
               existing_server_default=sa.text('false'))
    # 删除外键约束 - 需要指定约束名称
    op.execute("ALTER TABLE dic_enums DROP CONSTRAINT IF EXISTS dic_enums_parent_id_fkey")
    op.drop_column('dic_enums', 'path')
    op.drop_column('dic_enums', 'level')
    op.drop_column('dic_enums', 'parent_id')
    # ### end Alembic commands ###
