"""add_cascade_fields_to_dictionary_enum

Revision ID: 6651bd40ebda
Revises: c293cfa96ab9
Create Date: 2025-09-07 17:20:52.257097

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6651bd40ebda'
down_revision = 'c293cfa96ab9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
    op.drop_index(op.f('ix_system_settings_setting_key'), table_name='system_settings')
    op.drop_table('system_settings')
    op.add_column('dic_enums', sa.Column('parent_id', sa.Integer(), nullable=True, comment='父级枚举ID'))
    op.add_column('dic_enums', sa.Column('level', sa.Integer(), nullable=True, comment='层级'))
    op.add_column('dic_enums', sa.Column('path', sa.String(), nullable=True, comment='路径'))
    op.create_foreign_key(None, 'dic_enums', 'dic_enums', ['parent_id'], ['id'])
    op.alter_column('menus', 'is_link',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_comment='是否外链',
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('menus', 'is_link',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_comment='是否外链',
               existing_server_default=sa.text('false'))
    op.drop_constraint(None, 'dic_enums', type_='foreignkey')
    op.drop_column('dic_enums', 'path')
    op.drop_column('dic_enums', 'level')
    op.drop_column('dic_enums', 'parent_id')
    op.create_table('system_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('create_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('create_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('update_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('update_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('status', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('setting_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('setting_value', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('setting_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('setting_desc', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('system_settings_pkey')),
    sa.UniqueConstraint('setting_key', name=op.f('system_settings_setting_key_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_system_settings_setting_key'), 'system_settings', ['setting_key'], unique=False)
    op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=False)
    # ### end Alembic commands ###
