"""add_role_menu_association_table

Revision ID: 87b3f539ff95
Revises: 1a5d49a84516
Create Date: 2025-08-20 17:05:09.845733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87b3f539ff95'
down_revision = '1a5d49a84516'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_menu',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'menu_id')
    )
    op.alter_column('menus', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='菜单名称',
               existing_nullable=False)
    op.alter_column('menus', 'path',
               existing_type=sa.VARCHAR(length=200),
               comment='路由地址',
               existing_nullable=True)
    op.alter_column('menus', 'component',
               existing_type=sa.VARCHAR(length=200),
               comment='组件路径',
               existing_nullable=True)
    op.alter_column('menus', 'redirect',
               existing_type=sa.VARCHAR(length=200),
               comment='重定向地址',
               existing_nullable=True)
    op.alter_column('menus', 'title',
               existing_type=sa.VARCHAR(length=100),
               comment='菜单标题',
               existing_nullable=False)
    op.alter_column('menus', 'icon',
               existing_type=sa.VARCHAR(length=100),
               comment='菜单图标',
               existing_nullable=True)
    op.alter_column('menus', 'sort',
               existing_type=sa.INTEGER(),
               comment='菜单排序',
               existing_nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('menus', 'is_hide',
               existing_type=sa.BOOLEAN(),
               comment='是否隐藏',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('menus', 'is_keep_alive',
               existing_type=sa.BOOLEAN(),
               comment='是否缓存',
               existing_nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('menus', 'is_iframe',
               existing_type=sa.BOOLEAN(),
               comment='是否内嵌',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('menus', 'link',
               existing_type=sa.VARCHAR(length=500),
               comment='外部链接',
               existing_nullable=True)
    op.alter_column('menus', 'is_enable',
               existing_type=sa.BOOLEAN(),
               comment='是否启用',
               existing_nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('menus', 'menu_type',
               existing_type=sa.VARCHAR(length=20),
               comment='菜单类型：menu-菜单，button-权限',
               existing_nullable=True,
               existing_server_default=sa.text("'menu'::character varying"))
    op.alter_column('menus', 'parent_id',
               existing_type=sa.INTEGER(),
               comment='父菜单ID',
               existing_nullable=True)
    op.alter_column('menus', 'auth_name',
               existing_type=sa.VARCHAR(length=100),
               comment='权限名称',
               existing_nullable=True)
    op.alter_column('menus', 'auth_mark',
               existing_type=sa.VARCHAR(length=100),
               comment='权限标识',
               existing_nullable=True)
    op.alter_column('menus', 'auth_sort',
               existing_type=sa.INTEGER(),
               comment='权限排序',
               existing_nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('menus', 'create_by',
               existing_type=sa.VARCHAR(length=255),
               comment='创建者',
               existing_nullable=True)
    op.alter_column('menus', 'update_by',
               existing_type=sa.VARCHAR(length=255),
               comment='更新者',
               existing_nullable=True)
    op.drop_index(op.f('ix_menus_name'), table_name='menus')
    op.drop_index(op.f('ix_menus_path'), table_name='menus')
    op.drop_column('menus', 'roles')
    op.alter_column('roles', 'role_name',
               existing_type=sa.VARCHAR(length=50),
               comment='角色名称',
               existing_nullable=False)
    op.alter_column('roles', 'role_code',
               existing_type=sa.VARCHAR(length=50),
               comment='角色编码',
               existing_nullable=False)
    op.alter_column('roles', 'description',
               existing_type=sa.TEXT(),
               comment='角色描述',
               existing_nullable=True)
    op.alter_column('roles', 'status',
               existing_type=sa.BOOLEAN(),
               comment='启用状态',
               existing_nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('roles', 'create_by',
               existing_type=sa.VARCHAR(length=50),
               comment='创建人',
               existing_nullable=True)
    op.alter_column('roles', 'update_by',
               existing_type=sa.VARCHAR(length=50),
               comment='更新人',
               existing_nullable=True)
    op.drop_constraint(op.f('roles_role_code_key'), 'roles', type_='unique')
    op.drop_constraint(op.f('roles_role_name_key'), 'roles', type_='unique')
    op.drop_index(op.f('ix_roles_role_code'), table_name='roles')
    op.create_index(op.f('ix_roles_role_code'), 'roles', ['role_code'], unique=True)
    op.drop_index(op.f('ix_roles_role_name'), table_name='roles')
    op.create_index(op.f('ix_roles_role_name'), 'roles', ['role_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_role_name'), table_name='roles')
    op.create_index(op.f('ix_roles_role_name'), 'roles', ['role_name'], unique=False)
    op.drop_index(op.f('ix_roles_role_code'), table_name='roles')
    op.create_index(op.f('ix_roles_role_code'), 'roles', ['role_code'], unique=False)
    op.create_unique_constraint(op.f('roles_role_name_key'), 'roles', ['role_name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('roles_role_code_key'), 'roles', ['role_code'], postgresql_nulls_not_distinct=False)
    op.alter_column('roles', 'update_by',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='更新人',
               existing_nullable=True)
    op.alter_column('roles', 'create_by',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='创建人',
               existing_nullable=True)
    op.alter_column('roles', 'status',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='启用状态',
               existing_nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('roles', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='角色描述',
               existing_nullable=True)
    op.alter_column('roles', 'role_code',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='角色编码',
               existing_nullable=False)
    op.alter_column('roles', 'role_name',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='角色名称',
               existing_nullable=False)
    op.add_column('menus', sa.Column('roles', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_menus_path'), 'menus', ['path'], unique=False)
    op.create_index(op.f('ix_menus_name'), 'menus', ['name'], unique=True)
    op.alter_column('menus', 'update_by',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='更新者',
               existing_nullable=True)
    op.alter_column('menus', 'create_by',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='创建者',
               existing_nullable=True)
    op.alter_column('menus', 'auth_sort',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='权限排序',
               existing_nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('menus', 'auth_mark',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='权限标识',
               existing_nullable=True)
    op.alter_column('menus', 'auth_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='权限名称',
               existing_nullable=True)
    op.alter_column('menus', 'parent_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='父菜单ID',
               existing_nullable=True)
    op.alter_column('menus', 'menu_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='菜单类型：menu-菜单，button-权限',
               existing_nullable=True,
               existing_server_default=sa.text("'menu'::character varying"))
    op.alter_column('menus', 'is_enable',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否启用',
               existing_nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('menus', 'link',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='外部链接',
               existing_nullable=True)
    op.alter_column('menus', 'is_iframe',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否内嵌',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('menus', 'is_keep_alive',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否缓存',
               existing_nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('menus', 'is_hide',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否隐藏',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('menus', 'sort',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='菜单排序',
               existing_nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('menus', 'icon',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='菜单图标',
               existing_nullable=True)
    op.alter_column('menus', 'title',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='菜单标题',
               existing_nullable=False)
    op.alter_column('menus', 'redirect',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='重定向地址',
               existing_nullable=True)
    op.alter_column('menus', 'component',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='组件路径',
               existing_nullable=True)
    op.alter_column('menus', 'path',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='路由地址',
               existing_nullable=True)
    op.alter_column('menus', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='菜单名称',
               existing_nullable=False)
    op.drop_table('role_menu')
    # ### end Alembic commands ###
