"""Add missing order detail tables

Revision ID: a9267fb3f204
Revises: 001_initial_migration
Create Date: 2025-09-11 04:48:26.993507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9267fb3f204'
down_revision = '001_initial_migration'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dic_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(), nullable=False, comment='字典类型名称'),
    sa.Column('code', sa.String(), nullable=False, comment='字典类型编码'),
    sa.Column('description', sa.String(), nullable=True, comment='字典类型描述'),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True, comment='创建者'),
    sa.Column('updated_by', sa.String(length=100), nullable=True, comment='更新者'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dic_type_code'), 'dic_type', ['code'], unique=True)
    op.create_index(op.f('ix_dic_type_id'), 'dic_type', ['id'], unique=False)
    op.create_index(op.f('ix_dic_type_name'), 'dic_type', ['name'], unique=True)
    op.create_table('menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='菜单名称'),
    sa.Column('path', sa.String(length=200), nullable=True, comment='路由地址'),
    sa.Column('icon', sa.String(length=100), nullable=True, comment='菜单图标'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='菜单排序'),
    sa.Column('is_hide', sa.Boolean(), nullable=True, comment='是否隐藏'),
    sa.Column('is_keep_alive', sa.Boolean(), nullable=True, comment='是否缓存'),
    sa.Column('is_link', sa.Boolean(), nullable=True, comment='是否外链'),
    sa.Column('link', sa.String(length=500), nullable=True, comment='外部链接'),
    sa.Column('is_enable', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('menu_type', sa.String(length=20), nullable=True, comment='菜单类型：menu-菜单，button-权限'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父菜单ID'),
    sa.Column('auth_mark', sa.String(length=100), nullable=True, comment='权限标识'),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True, comment='创建者'),
    sa.Column('updated_by', sa.String(length=100), nullable=True, comment='更新者'),
    sa.ForeignKeyConstraint(['parent_id'], ['menu.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_id'), 'menu', ['id'], unique=False)
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=False, comment='角色名称'),
    sa.Column('role_code', sa.String(length=50), nullable=False, comment='角色编码'),
    sa.Column('description', sa.Text(), nullable=True, comment='角色描述'),
    sa.Column('status', sa.Boolean(), nullable=True, comment='启用状态'),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True, comment='创建者'),
    sa.Column('updated_by', sa.String(length=100), nullable=True, comment='更新者'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_id'), 'role', ['id'], unique=False)
    op.create_index(op.f('ix_role_role_code'), 'role', ['role_code'], unique=True)
    op.create_index(op.f('ix_role_role_name'), 'role', ['role_name'], unique=True)
    op.create_table('system_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('setting_key', sa.String(), nullable=False, comment='配置键'),
    sa.Column('setting_value', sa.String(), nullable=False, comment='配置值'),
    sa.Column('setting_name', sa.String(), nullable=False, comment='配置名称'),
    sa.Column('setting_desc', sa.String(), nullable=True, comment='配置描述'),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True, comment='创建者'),
    sa.Column('updated_by', sa.String(length=100), nullable=True, comment='更新者'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_setting_id'), 'system_setting', ['id'], unique=False)
    op.create_index(op.f('ix_system_setting_setting_key'), 'system_setting', ['setting_key'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('nick_name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True, comment='创建者'),
    sa.Column('updated_by', sa.String(length=100), nullable=True, comment='更新者'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_user_name'), 'user', ['user_name'], unique=True)
    op.create_table('dic_enum',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=False, comment='字典类型ID'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父级枚举ID'),
    sa.Column('key_value', sa.String(), nullable=False, comment='键值'),
    sa.Column('dict_value', sa.String(), nullable=False, comment='字典值'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('level', sa.Integer(), nullable=True, comment='层级'),
    sa.Column('path', sa.String(), nullable=True, comment='路径'),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True, comment='创建者'),
    sa.Column('updated_by', sa.String(length=100), nullable=True, comment='更新者'),
    sa.ForeignKeyConstraint(['parent_id'], ['dic_enum.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['dic_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dic_enum_id'), 'dic_enum', ['id'], unique=False)
    op.create_table('external_order',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('customer', sa.String(), nullable=False),
    sa.Column('vehicle_model', sa.String(), nullable=False),
    sa.Column('repair_shop', sa.String(), nullable=False),
    sa.Column('reporter_name', sa.String(), nullable=False),
    sa.Column('contact_info', sa.String(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('project_type', sa.String(), nullable=False),
    sa.Column('project_stage', sa.String(), nullable=False),
    sa.Column('license_plate', sa.String(), nullable=True),
    sa.Column('vin_number', sa.String(), nullable=False),
    sa.Column('mileage', sa.Float(), nullable=True),
    sa.Column('vehicle_location', sa.Text(), nullable=True),
    sa.Column('vehicle_date', sa.Date(), nullable=True),
    sa.Column('pack_code', sa.String(), nullable=True),
    sa.Column('pack_date', sa.Date(), nullable=True),
    sa.Column('under_warranty', sa.Boolean(), nullable=True),
    sa.Column('fault_description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True, comment='更新者'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_external_order_id'), 'external_order', ['id'], unique=False)
    op.create_table('internal_order',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('customer', sa.String(), nullable=False),
    sa.Column('vehicle_model', sa.String(), nullable=False),
    sa.Column('repair_shop', sa.String(), nullable=False),
    sa.Column('reporter_name', sa.String(), nullable=False),
    sa.Column('contact_info', sa.String(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('project_type', sa.String(), nullable=False),
    sa.Column('project_stage', sa.String(), nullable=False),
    sa.Column('license_plate', sa.String(), nullable=True),
    sa.Column('vin_number', sa.String(), nullable=False),
    sa.Column('mileage', sa.Float(), nullable=True),
    sa.Column('vehicle_location', sa.Text(), nullable=True),
    sa.Column('vehicle_date', sa.Date(), nullable=True),
    sa.Column('pack_code', sa.String(), nullable=True),
    sa.Column('pack_date', sa.Date(), nullable=True),
    sa.Column('under_warranty', sa.Boolean(), nullable=True),
    sa.Column('fault_description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True, comment='更新者'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_internal_order_id'), 'internal_order', ['id'], unique=False)
    op.create_table('role_menu',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['menu.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'menu_id')
    )
    op.create_table('user_role',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('external_order_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('repair_person', sa.String(), nullable=True),
    sa.Column('repair_date', sa.Date(), nullable=True),
    sa.Column('avic_responsibility', sa.Boolean(), nullable=True),
    sa.Column('fault_classification', sa.String(), nullable=True),
    sa.Column('fault_location', sa.String(), nullable=True),
    sa.Column('part_category', sa.String(), nullable=True),
    sa.Column('part_location', sa.String(), nullable=True),
    sa.Column('repair_description', sa.Text(), nullable=True),
    sa.Column('spare_part_location', sa.String(), nullable=True),
    sa.Column('spare_parts', sa.JSON(), nullable=True),
    sa.Column('costs', sa.JSON(), nullable=True),
    sa.Column('labors', sa.JSON(), nullable=True),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True, comment='创建者'),
    sa.Column('updated_by', sa.String(length=100), nullable=True, comment='更新者'),
    sa.ForeignKeyConstraint(['order_id'], ['external_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_external_order_detail_id'), 'external_order_detail', ['id'], unique=False)
    op.create_index(op.f('ix_external_order_detail_order_id'), 'external_order_detail', ['order_id'], unique=False)
    op.create_table('internal_order_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('repair_person', sa.String(), nullable=True),
    sa.Column('repair_date', sa.Date(), nullable=True),
    sa.Column('avic_responsibility', sa.Boolean(), nullable=True),
    sa.Column('fault_classification', sa.String(), nullable=True),
    sa.Column('fault_location', sa.String(), nullable=True),
    sa.Column('part_category', sa.String(), nullable=True),
    sa.Column('part_location', sa.String(), nullable=True),
    sa.Column('repair_description', sa.Text(), nullable=True),
    sa.Column('spare_part_location', sa.String(), nullable=True),
    sa.Column('spare_parts', sa.JSON(), nullable=True),
    sa.Column('costs', sa.JSON(), nullable=True),
    sa.Column('labors', sa.JSON(), nullable=True),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True, comment='创建者'),
    sa.Column('updated_by', sa.String(length=100), nullable=True, comment='更新者'),
    sa.ForeignKeyConstraint(['order_id'], ['internal_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_internal_order_detail_id'), 'internal_order_detail', ['id'], unique=False)
    op.create_index(op.f('ix_internal_order_detail_order_id'), 'internal_order_detail', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_internal_order_detail_order_id'), table_name='internal_order_detail')
    op.drop_index(op.f('ix_internal_order_detail_id'), table_name='internal_order_detail')
    op.drop_table('internal_order_detail')
    op.drop_index(op.f('ix_external_order_detail_order_id'), table_name='external_order_detail')
    op.drop_index(op.f('ix_external_order_detail_id'), table_name='external_order_detail')
    op.drop_table('external_order_detail')
    op.drop_table('user_role')
    op.drop_table('role_menu')
    op.drop_index(op.f('ix_internal_order_id'), table_name='internal_order')
    op.drop_table('internal_order')
    op.drop_index(op.f('ix_external_order_id'), table_name='external_order')
    op.drop_table('external_order')
    op.drop_index(op.f('ix_dic_enum_id'), table_name='dic_enum')
    op.drop_table('dic_enum')
    op.drop_index(op.f('ix_user_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_system_setting_setting_key'), table_name='system_setting')
    op.drop_index(op.f('ix_system_setting_id'), table_name='system_setting')
    op.drop_table('system_setting')
    op.drop_index(op.f('ix_role_role_name'), table_name='role')
    op.drop_index(op.f('ix_role_role_code'), table_name='role')
    op.drop_index(op.f('ix_role_id'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_menu_id'), table_name='menu')
    op.drop_table('menu')
    op.drop_index(op.f('ix_dic_type_name'), table_name='dic_type')
    op.drop_index(op.f('ix_dic_type_id'), table_name='dic_type')
    op.drop_index(op.f('ix_dic_type_code'), table_name='dic_type')
    op.drop_table('dic_type')
    # ### end Alembic commands ###
