"""add_labors_field_to_order_details

Revision ID: a93b2aa2654d
Revises: cf39a4f6fb85
Create Date: 2025-09-08 13:38:57.817243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a93b2aa2654d'
down_revision = 'cf39a4f6fb85'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('external_order_details', sa.Column('labors', sa.JSON(), nullable=True))
    op.add_column('internal_order_details', sa.Column('labors', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('internal_order_details', 'labors')
    op.drop_column('external_order_details', 'labors')
    # ### end Alembic commands ###
