"""add menu table

Revision ID: add_menu_table
Revises: ff3530c282a6
Create Date: 2025-01-27 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_menu_table'
down_revision = 'ff3530c282a6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('path', sa.String(length=200), nullable=True),
    sa.Column('component', sa.String(length=200), nullable=True),
    sa.Column('redirect', sa.String(length=200), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.Column('is_hide', sa.Boolean(), nullable=True),
    sa.Column('is_keep_alive', sa.Boolean(), nullable=True),
    sa.Column('is_iframe', sa.Boolean(), nullable=True),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('is_enable', sa.Boolean(), nullable=True),
    sa.Column('menu_type', sa.String(length=20), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('roles', sa.Text(), nullable=True),
    sa.Column('auth_name', sa.String(length=100), nullable=True),
    sa.Column('auth_mark', sa.String(length=100), nullable=True),
    sa.Column('auth_sort', sa.Integer(), nullable=True),
    sa.Column('create_by', sa.String(), nullable=True),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_by', sa.String(), nullable=True),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['menus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menus_id'), 'menus', ['id'], unique=False)
    op.create_index(op.f('ix_menus_name'), 'menus', ['name'], unique=True)
    op.create_index(op.f('ix_menus_path'), 'menus', ['path'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_menus_path'), table_name='menus')
    op.drop_index(op.f('ix_menus_name'), table_name='menus')
    op.drop_index(op.f('ix_menus_id'), table_name='menus')
    op.drop_table('menus')
    # ### end Alembic commands ###
