"""add created_by and updated_by fields to all tables

Revision ID: 5ade689e618
Revises: de7bded54dd
Create Date: 2025-01-27 17:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ade689e618'
down_revision = 'de7bded54dd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 为用户表添加创建者和更新者字段
    op.add_column('users', sa.Column('created_by', sa.String(100), nullable=True, comment='创建者'))
    op.add_column('users', sa.Column('updated_by', sa.String(100), nullable=True, comment='更新者'))
    
    # 为菜单表添加创建者和更新者字段
    op.add_column('menus', sa.Column('created_by', sa.String(100), nullable=True, comment='创建者'))
    op.add_column('menus', sa.Column('updated_by', sa.String(100), nullable=True, comment='更新者'))
    
    # 为角色表添加创建者和更新者字段
    op.add_column('roles', sa.Column('created_by', sa.String(100), nullable=True, comment='创建者'))
    op.add_column('roles', sa.Column('updated_by', sa.String(100), nullable=True, comment='更新者'))
    
    # 为字典类型表添加创建者和更新者字段
    op.add_column('dic_types', sa.Column('created_by', sa.String(100), nullable=True, comment='创建者'))
    op.add_column('dic_types', sa.Column('updated_by', sa.String(100), nullable=True, comment='更新者'))
    
    # 为字典枚举表添加创建者和更新者字段
    op.add_column('dic_enums', sa.Column('created_by', sa.String(100), nullable=True, comment='创建者'))
    op.add_column('dic_enums', sa.Column('updated_by', sa.String(100), nullable=True, comment='更新者'))
    
    # 为系统配置表添加创建者和更新者字段
    op.add_column('system_settings', sa.Column('created_by', sa.String(100), nullable=True, comment='创建者'))
    op.add_column('system_settings', sa.Column('updated_by', sa.String(100), nullable=True, comment='更新者'))
    
    # 为工单表添加updated_by字段（created_by已存在）
    op.add_column('internal_orders', sa.Column('updated_by', sa.String(100), nullable=True, comment='更新者'))
    op.add_column('external_orders', sa.Column('updated_by', sa.String(100), nullable=True, comment='更新者'))
    
    # 为工单详情表添加创建者和更新者字段
    op.add_column('internal_order_details', sa.Column('created_by', sa.String(100), nullable=True, comment='创建者'))
    op.add_column('internal_order_details', sa.Column('updated_by', sa.String(100), nullable=True, comment='更新者'))
    
    op.add_column('external_order_details', sa.Column('created_by', sa.String(100), nullable=True, comment='创建者'))
    op.add_column('external_order_details', sa.Column('updated_by', sa.String(100), nullable=True, comment='更新者'))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 删除工单表的创建者和更新者字段
    op.drop_column('external_order_details', 'updated_by')
    op.drop_column('external_order_details', 'created_by')
    op.drop_column('internal_order_details', 'updated_by')
    op.drop_column('internal_order_details', 'created_by')
    op.drop_column('external_orders', 'updated_by')
    op.drop_column('external_orders', 'created_by')
    op.drop_column('internal_orders', 'updated_by')
    op.drop_column('internal_orders', 'created_by')
    
    # 删除系统配置表的创建者和更新者字段
    op.drop_column('system_settings', 'updated_by')
    op.drop_column('system_settings', 'created_by')
    
    # 删除字典表的创建者和更新者字段
    op.drop_column('dic_enums', 'updated_by')
    op.drop_column('dic_enums', 'created_by')
    op.drop_column('dic_types', 'updated_by')
    op.drop_column('dic_types', 'created_by')
    
    # 删除角色表的创建者和更新者字段
    op.drop_column('roles', 'updated_by')
    op.drop_column('roles', 'created_by')
    
    # 删除菜单表的创建者和更新者字段
    op.drop_column('menus', 'updated_by')
    op.drop_column('menus', 'created_by')
    
    # 删除用户表的创建者和更新者字段
    op.drop_column('users', 'updated_by')
    op.drop_column('users', 'created_by')
    
    # ### end Alembic commands ###
