"""add unique constraints to order ids

Revision ID: 51aa96a9f40
Revises: 47e2bd333d83
Create Date: 2025-01-27 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51aa96a9f40'
down_revision = '47e2bd333d83'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 为工单表添加唯一约束，确保ID的唯一性
    op.create_unique_constraint('uk_internal_orders_id', 'internal_orders', ['id'])
    op.create_unique_constraint('uk_external_orders_id', 'external_orders', ['id'])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 删除唯一约束
    op.drop_constraint('uk_external_orders_id', 'external_orders', type_='unique')
    op.drop_constraint('uk_internal_orders_id', 'internal_orders', type_='unique')
    
    # ### end Alembic commands ###
