"""add_order_progress_field

Revision ID: add_order_progress_field
Revises: 5c8c9d6a07c1
Create Date: 2025-09-28 14:44:48.865970

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'add_order_progress_field'
down_revision = '5c8c9d6a07c1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 为保内工单表添加工单进度字段
    op.add_column('internal_order', sa.Column('order_progress', sa.Text(), nullable=True))
    
    # 为保外工单表添加工单进度字段
    op.add_column('external_order', sa.Column('order_progress', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 删除保内工单表的工单进度字段
    op.drop_column('internal_order', 'order_progress')
    
    # 删除保外工单表的工单进度字段
    op.drop_column('external_order', 'order_progress')
    # ### end Alembic commands ###
