"""add timestamp fields to dictionary tables

Revision ID: de7bded54dd
Revises: 4c2ba8eee84
Create Date: 2025-01-27 16:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de7bded54dd'
down_revision = '4c2ba8eee84'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 为字典类型表添加时间戳字段
    op.add_column('dic_types', sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('dic_types', sa.Column('update_time', sa.DateTime(timezone=True), nullable=True))
    
    # 为字典枚举表添加时间戳字段
    op.add_column('dic_enums', sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('dic_enums', sa.Column('update_time', sa.DateTime(timezone=True), nullable=True))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 删除时间戳字段
    op.drop_column('dic_enums', 'update_time')
    op.drop_column('dic_enums', 'create_time')
    op.drop_column('dic_types', 'update_time')
    op.drop_column('dic_types', 'create_time')
    
    # ### end Alembic commands ###
