"""Add avic_order_number to internal_order

Revision ID: add_avic_order_number
Revises: 9560c2d2a332
Create Date: 2025-10-05 22:40:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'add_avic_order_number'
down_revision = '9560c2d2a332'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('internal_order', sa.Column('avic_order_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('internal_order', 'avic_order_number')
    # ### end Alembic commands ###
