"""recreate_system_settings_table

Revision ID: af942f98b9ca
Revises: cfa8b19b4857
Create Date: 2025-09-08 13:41:46.225827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af942f98b9ca'
down_revision = 'cfa8b19b4857'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
