"""add_order_detail_tables

Revision ID: cf39a4f6fb85
Revises: 6651bd40ebda
Create Date: 2025-09-08 13:35:19.012282

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cf39a4f6fb85'
down_revision = '6651bd40ebda'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_order_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('repair_person', sa.String(), nullable=True),
    sa.Column('repair_date', sa.Date(), nullable=True),
    sa.Column('avic_responsibility', sa.Boolean(), nullable=True),
    sa.Column('fault_classification', sa.String(), nullable=True),
    sa.Column('fault_location', sa.String(), nullable=True),
    sa.Column('part_category', sa.String(), nullable=True),
    sa.Column('part_location', sa.String(), nullable=True),
    sa.Column('repair_description', sa.Text(), nullable=True),
    sa.Column('spare_part_location', sa.String(), nullable=True),
    sa.Column('spare_parts', sa.JSON(), nullable=True),
    sa.Column('costs', sa.JSON(), nullable=True),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_external_order_details_id'), 'external_order_details', ['id'], unique=False)
    op.create_index(op.f('ix_external_order_details_order_id'), 'external_order_details', ['order_id'], unique=False)
    op.create_table('internal_order_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('repair_person', sa.String(), nullable=True),
    sa.Column('repair_date', sa.Date(), nullable=True),
    sa.Column('avic_responsibility', sa.Boolean(), nullable=True),
    sa.Column('fault_classification', sa.String(), nullable=True),
    sa.Column('fault_location', sa.String(), nullable=True),
    sa.Column('part_category', sa.String(), nullable=True),
    sa.Column('part_location', sa.String(), nullable=True),
    sa.Column('repair_description', sa.Text(), nullable=True),
    sa.Column('spare_part_location', sa.String(), nullable=True),
    sa.Column('spare_parts', sa.JSON(), nullable=True),
    sa.Column('costs', sa.JSON(), nullable=True),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_internal_order_details_id'), 'internal_order_details', ['id'], unique=False)
    op.create_index(op.f('ix_internal_order_details_order_id'), 'internal_order_details', ['order_id'], unique=False)
    op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
    op.drop_index(op.f('ix_system_settings_setting_key'), table_name='system_settings')
    op.drop_table('system_settings')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('create_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('create_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('update_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('update_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('status', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('setting_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('setting_value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('setting_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('setting_desc', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('setting_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('system_settings_pkey'))
    )
    op.create_index(op.f('ix_system_settings_setting_key'), 'system_settings', ['setting_key'], unique=True)
    op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=False)
    op.drop_index(op.f('ix_internal_order_details_order_id'), table_name='internal_order_details')
    op.drop_index(op.f('ix_internal_order_details_id'), table_name='internal_order_details')
    op.drop_table('internal_order_details')
    op.drop_index(op.f('ix_external_order_details_order_id'), table_name='external_order_details')
    op.drop_index(op.f('ix_external_order_details_id'), table_name='external_order_details')
    op.drop_table('external_order_details')
    # ### end Alembic commands ###
