"""add_foreign_keys_to_order_details

Revision ID: cfa8b19b4857
Revises: a93b2aa2654d
Create Date: 2025-09-08 13:40:10.193231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfa8b19b4857'
down_revision = 'a93b2aa2654d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'external_order_details', 'external_orders', ['order_id'], ['id'])
    op.create_foreign_key(None, 'internal_order_details', 'internal_orders', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'internal_order_details', type_='foreignkey')
    op.drop_constraint(None, 'external_order_details', type_='foreignkey')
    # ### end Alembic commands ###
