"""rename_time_fields_correctly

Revision ID: cfaae8395505
Revises: 53997f50e5cf
Create Date: 2025-08-19 17:17:20.568165

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cfaae8395505'
down_revision = '53997f50e5cf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('customers', sa.Column('update_time', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('customers', 'updated_at')
    op.drop_column('customers', 'created_at')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('customers', 'update_time')
    op.drop_column('customers', 'create_time')
    # ### end Alembic commands ###
