"""add_order_tables

Revision ID: d71ba87be685
Revises: 0e24ef6757e2
Create Date: 2025-09-04 11:14:25.623397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd71ba87be685'
down_revision = '0e24ef6757e2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_orders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('customer', sa.String(), nullable=False),
    sa.Column('reporter_name', sa.String(), nullable=False),
    sa.Column('contact_info', sa.String(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('project_type', sa.String(), nullable=False),
    sa.Column('project_stage', sa.String(), nullable=False),
    sa.Column('license_plate', sa.String(), nullable=True),
    sa.Column('vin_number', sa.String(), nullable=False),
    sa.Column('mileage', sa.Float(), nullable=True),
    sa.Column('vehicle_location', sa.Text(), nullable=True),
    sa.Column('vehicle_date', sa.Date(), nullable=True),
    sa.Column('pack_code', sa.String(), nullable=True),
    sa.Column('pack_date', sa.Date(), nullable=True),
    sa.Column('under_warranty', sa.Boolean(), nullable=True),
    sa.Column('fault_description', sa.Text(), nullable=True),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_external_orders_id'), 'external_orders', ['id'], unique=False)
    op.create_table('internal_orders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('customer', sa.String(), nullable=False),
    sa.Column('reporter_name', sa.String(), nullable=False),
    sa.Column('contact_info', sa.String(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('project_type', sa.String(), nullable=False),
    sa.Column('project_stage', sa.String(), nullable=False),
    sa.Column('license_plate', sa.String(), nullable=True),
    sa.Column('vin_number', sa.String(), nullable=False),
    sa.Column('mileage', sa.Float(), nullable=True),
    sa.Column('vehicle_location', sa.Text(), nullable=True),
    sa.Column('vehicle_date', sa.Date(), nullable=True),
    sa.Column('pack_code', sa.String(), nullable=True),
    sa.Column('pack_date', sa.Date(), nullable=True),
    sa.Column('under_warranty', sa.Boolean(), nullable=True),
    sa.Column('fault_description', sa.Text(), nullable=True),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_internal_orders_id'), 'internal_orders', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_internal_orders_id'), table_name='internal_orders')
    op.drop_table('internal_orders')
    op.drop_index(op.f('ix_external_orders_id'), table_name='external_orders')
    op.drop_table('external_orders')
    # ### end Alembic commands ###
