"""add_dictionary_tables

Revision ID: e736852c7081
Revises: cfaae8395505
Create Date: 2025-08-19 21:07:28.687128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e736852c7081'
down_revision = 'cfaae8395505'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dic_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_by', sa.String(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_by', sa.String(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(), nullable=False, comment='字典类型名称'),
    sa.Column('code', sa.String(), nullable=False, comment='字典类型编码'),
    sa.Column('description', sa.String(), nullable=True, comment='字典类型描述'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dic_types_code'), 'dic_types', ['code'], unique=True)
    op.create_index(op.f('ix_dic_types_id'), 'dic_types', ['id'], unique=False)
    op.create_index(op.f('ix_dic_types_name'), 'dic_types', ['name'], unique=True)
    op.create_table('dic_enums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_by', sa.String(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_by', sa.String(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=False, comment='字典类型ID'),
    sa.Column('key_value', sa.String(), nullable=False, comment='键值'),
    sa.Column('dict_value', sa.String(), nullable=False, comment='字典值'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='排序'),
    sa.ForeignKeyConstraint(['type_id'], ['dic_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dic_enums_id'), 'dic_enums', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dic_enums_id'), table_name='dic_enums')
    op.drop_table('dic_enums')
    op.drop_index(op.f('ix_dic_types_name'), table_name='dic_types')
    op.drop_index(op.f('ix_dic_types_id'), table_name='dic_types')
    op.drop_index(op.f('ix_dic_types_code'), table_name='dic_types')
    op.drop_table('dic_types')
    # ### end Alembic commands ###
