"""simplify table fields remove duplicate timestamp fields

Revision ID: 79743ec03e6
Revises: 51aa96a9f40
Create Date: 2025-01-27 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79743ec03e6'
down_revision = '51aa96a9f40'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 删除用户表中重复的时间戳字段
    op.drop_column('users', 'create_by')
    op.drop_column('users', 'create_time')
    op.drop_column('users', 'update_by')
    op.drop_column('users', 'update_time')
    
    # 修改用户表status字段类型为Boolean
    op.alter_column('users', 'status', type_=sa.Boolean(), nullable=True, postgresql_using='status::boolean')
    
    # 删除菜单表中重复的时间戳字段（roles字段不存在）
    op.drop_column('menus', 'create_by')
    op.drop_column('menus', 'update_by')
    
    # 删除角色表中重复的时间戳字段
    op.drop_column('roles', 'create_by')
    op.drop_column('roles', 'update_by')
    
    # 删除字典类型表中重复的时间戳字段
    op.drop_column('dic_types', 'create_by')
    op.drop_column('dic_types', 'create_time')
    op.drop_column('dic_types', 'update_by')
    op.drop_column('dic_types', 'update_time')
    
    # 删除字典枚举表中重复的时间戳字段
    op.drop_column('dic_enums', 'create_by')
    op.drop_column('dic_enums', 'create_time')
    op.drop_column('dic_enums', 'update_by')
    op.drop_column('dic_enums', 'update_time')
    
    # 删除系统配置表中重复的时间戳字段
    op.drop_column('system_settings', 'create_by')
    op.drop_column('system_settings', 'create_time')
    op.drop_column('system_settings', 'update_by')
    op.drop_column('system_settings', 'update_time')
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 恢复用户表字段
    op.add_column('users', sa.Column('create_by', sa.String(), nullable=True))
    op.add_column('users', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('update_by', sa.String(), nullable=True))
    op.add_column('users', sa.Column('update_time', sa.DateTime(), nullable=True))
    op.alter_column('users', 'status', type_=sa.String(), nullable=True)
    
    # 恢复菜单表字段
    op.add_column('menus', sa.Column('create_by', sa.String(255), nullable=True))
    op.add_column('menus', sa.Column('update_by', sa.String(255), nullable=True))
    op.add_column('menus', sa.Column('roles', sa.Text(), nullable=True))
    
    # 恢复角色表字段
    op.add_column('roles', sa.Column('create_by', sa.String(50), nullable=True))
    op.add_column('roles', sa.Column('update_by', sa.String(50), nullable=True))
    
    # 恢复字典类型表字段
    op.add_column('dic_types', sa.Column('create_by', sa.String(), nullable=True))
    op.add_column('dic_types', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('dic_types', sa.Column('update_by', sa.String(), nullable=True))
    op.add_column('dic_types', sa.Column('update_time', sa.DateTime(), nullable=True))
    
    # 恢复字典枚举表字段
    op.add_column('dic_enums', sa.Column('create_by', sa.String(), nullable=True))
    op.add_column('dic_enums', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('dic_enums', sa.Column('update_by', sa.String(), nullable=True))
    op.add_column('dic_enums', sa.Column('update_time', sa.DateTime(), nullable=True))
    
    # 恢复系统配置表字段
    op.add_column('system_settings', sa.Column('create_by', sa.String(), nullable=True))
    op.add_column('system_settings', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('system_settings', sa.Column('update_by', sa.String(), nullable=True))
    op.add_column('system_settings', sa.Column('update_time', sa.DateTime(), nullable=True))
    
    # 恢复客户表
    op.create_table('customers',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('email', sa.String(), nullable=True),
        sa.Column('phone', sa.String(), nullable=True),
        sa.Column('company', sa.String(), nullable=True),
        sa.Column('position', sa.String(), nullable=True),
        sa.Column('address', sa.Text(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_by', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=True)
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    
    # ### end Alembic commands ###
